### ISSUE TITLE
Recent vscode/git fail to run

### ISSUE THREAD

**Issue by jeluard** [eclipse-theia/vscode-builtin-extensions#52] opened 2021-03-11 14:57 UTC
With latest theia (`1.11`), recent versions of `vscode/git` fail with the following error:

```js
root ERROR [hosted-plugin: 47065] Activating extension 'Git (built-in)' failed: TypeError: n.window.registerFileDecorationProvider is not a function
    at new c (/Users/julien/theia/plugins/vscode-builtin-git/extension/dist/main.js:10:470092)
    at new t.GitDecorations (/Users/julien/theia/plugins/vscode-builtin-git/extension/dist/main.js:10:472492)
    at C (/Users/julien/theia/plugins/vscode-builtin-git/extension/dist/main.js:1:104831)
```

It appears that some VSCode API has been renamed: https://github.com/microsoft/vscode/commit/d04f3178dc9cc8823d8f799d65cad678c4ef3309

**Comment by jeluard** [comment] 2021-03-12 10:14
I'll take a look! Should the older name (`registerDecorationProvider `) still be available?

**Comment by azatsarynnyy** [comment] 2021-03-12 13:56
> I'll take a look! Should the older name (`registerDecorationProvider `) still be available?

I don't think so.

**Comment by vince-fugnitto** [comment] 2021-03-12 15:31
For the Eclipse Theia framework I believe it is already handled by the following pull-request:
- https://github.com/eclipse-theia/theia/pull/8911

**Comment by jeluard** [comment] 2021-03-12 15:51
@vince-fugnitto Good catch! I'll wait for the merge then!

**Comment by vince-fugnitto** [comment] 2021-06-18 18:54
Closing as the issue is related to the theia framework (fixed as part of https://github.com/eclipse-theia/theia/pull/8911), and not the publishing of builtins.

**Closed by vince-fugnitto** 2021-06-18 18:54 UTC
